### ISSUE TITLE
How to run the tests?  No module named 'sphinx_console'

### ISSUE THREAD

**Issue by szabgab** [zqmillet/sphinx-console#1]
I cloned the repo, installed the dependencies:

```
pip install -r sphinxcontrib/requirements.txt
```

I tried to run the tests locally, but I was not sure how. So I tried `pytest` but it was not required.

So:
```
pip install pytest
```

and then:

```
PYTHONPATH=. pytest
```

failed with this error:

```
============================= test session starts ==============================
platform linux -- Python 3.10.7, pytest-7.2.0, pluggy-1.0.0
rootdir: /opt
collected 4 items / 2 errors                                                   

==================================== ERRORS ====================================
__________________ ERROR collecting testcases/execute_test.py __________________
ImportError while importing test module '/opt/testcases/execute_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
testcases/execute_test.py:1: in <module>
    from sphinx_console.bash import execute
E   ModuleNotFoundError: No module named 'sphinx_console'
_____________ ERROR collecting testcases/interpret_python_test.py ______________
ImportError while importing test module '/opt/testcases/interpret_python_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
testcases/interpret_python_test.py:2: in <module>
    from sphinx_console.execute import interpret_python
E   ModuleNotFoundError: No module named 'sphinx_console'
=========================== short test summary info ============================
ERROR testcases/execute_test.py
ERROR testcases/interpret_python_test.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 2 errors in 0.18s ===============================

```

I guess I am doing something wrong.  How should I run the tests?

**Comment by zqmillet** [comment]
i'm sorry for not getting back to you sooner.

i've modified the directories of this project, but i forgot to change test cases.

**Comment by zqmillet** [comment]
i've fixed all bugs in testcases.

``` text
# kinopico @ macbook-pro in ~/Workspace/sphinx-console on git:main x [14:35:50] 
$ pytest testcases
============================ test session starts =============================
platform darwin -- Python 3.9.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/kinopico/Workspace/sphinx-console
collected 18 items                                                           

testcases/bash_test.py .                                               [  5%]
testcases/execute_test.py ......                                       [ 38%]
testcases/interpret_python_test.py ........                            [ 83%]
testcases/python_disassembly_test.py ..                                [ 94%]
testcases/python_test.py .                                             [100%]
```

**Comment by szabgab** [comment]
Thanks. It is still failing in my local Ubuntu Docker container and also when running on GitHub Actions. I sent you a PR #4 
You can use that to run the tests and see what might be the problem.

**Comment by zqmillet** [comment]
> Thanks. It is still failing in my local Ubuntu Docker container and also when running on GitHub Actions. I sent you a PR #4 You can use that to run the tests and see what might be the problem.

some flaky cases may exist in repo. i'll check them later.
